# Generated by Django 6.0.6 on 2026-06-10 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('memo', models.TextField(blank=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.bird')),
            ],
        ),
    ]
