# Generated by Django 6.0.6 on 2026-06-22 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_weightrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('memo', models.TextField()),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.bird')),
            ],
        ),
    ]
