# Generated by Django 6.0.7 on 2026-08-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_alter_behaviorrecord_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorrecord',
            name='category',
            field=models.CharField(choices=[('換羽', '換羽'), ('発情', '発情'), ('健康', '健康'), ('通院', '通院'), ('放鳥', '放鳥'), ('食事', '食事'), ('その他', 'その他')], max_length=20),
        ),
    ]
