# Generated by Django 6.0.7 on 2026-08-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0005_alter_behaviorrecord_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='welcome_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
