# Generated by Django 6.0.7 on 2026-08-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0006_bird_welcome_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='birds/'),
        ),
    ]
