# Generated by Django 6.0.7 on 2026-08-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0007_bird_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorrecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='behavior_photos/'),
        ),
    ]
